### ISSUE TITLE
some problems about import

### ISSUE THREAD

**Issue by CCV-Edward** [mknicklee/image-inpainting#1]
Hello mknicklee
    i am trying to reproduce your fantastic work, unfortunately i meet to some problems

 Import error:No module named inpainting

please give me some advice

**Comment by nlee737** [comment]
Hi CCV-Edward,

Apologies for the late reply. 
Although my work isn't fantastic by any means, thanks for checking out my project.

It looks like you're missing the _inpainting.so_ library. It's included in the repository. You should make sure it is in the same directory as _InpaintingGUI.py._
