### ISSUE TITLE
Error while running on some images

### ISSUE THREAD

**Issue by pradyoth-hegde** [mknicklee/image-inpainting#3]
Hi, I first ran your code for the "input.jpg" and the results were good.
But, then I tried running it for the other test images and some of the other images I had, but it gave me the same error while reading the mask.

![capture](https://cloud.githubusercontent.com/assets/25714487/23248729/8d117454-f966-11e6-9c48-e678b2814035.PNG)

The error was "Unsupported BMP header type (108)

Any help would be wonderful

Regards

**Comment by nlee737** [comment]
Hi,

Sorry, I don't know about that error. I created my bmp masks using GIMP. You might have to open the bmp masks in a shell and save it as a 2 dimensional numpy array.

Regards
