### ISSUE TITLE
ImportError: No module named inpainting

### ISSUE THREAD

**Issue by Aftab890** [mknicklee/image-inpainting#4]
Hello.

I am also facing this problem ImportError: No module named inpainting. I have installed

Python 2.7.13
Cython 0.25 
NumPy for Python 2
SciPy for Python 2
Matplotlib for Python 2
wxPython 4.0.0 

And also i have all your files in one folder, including inpainting.so and InpaintingGUI.py.
I am running windows 10. Kindly suggest me any solution

Thanks

**Comment by nlee737** [comment]
Hi Aftab890. 

The inpaining Cython module in the repository has been compiled in Linux so you will need to compile the C source code inpainting.c on Windows. 

Have a look at this page: https://github.com/cython/cython/wiki/CythonExtensionsOnWindows

I barely remember compiling the C module using MS Visual C++ compiler long ago. I cannot provide any more information than this. My apologies.
