### ISSUE TITLE
Why when I run on windows,error occurs?

### ISSUE THREAD

**Issue by zhushengwen** [mknicklee/image-inpainting#6]
D:\Desktop\image-inpainting>python D:\Desktop\image-inpainting\InpaintingGUI.py
Traceback (most recent call last):
  File "D:\Desktop\image-inpainting\InpaintingGUI.py", line 4, in <module>
    from inpainting import inpaint
ImportError: No module named inpainting

**Comment by nlee737** [comment]
You must compile the C code generated by Cython for Windows.
